networks:
  app:
    name: app
    driver: bridge

volumes:
  db-data:
    name: db-data
    driver: local
services:
  traffic-api:
    container_name: traffic-api
    build: ./traffic-api
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    ports:
      - "8000:8000"
    volumes:
      - ./traffic-api:/var/www/html
    environment:
      - HOME=/var/www/html
    networks:
      - app
    depends_on:
      - db
  dashboard:
    build: ./traffic-dashboard
    container_name: traffic-dashboard
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    ports:
      - '4200:4200'
    volumes:
      - ./traffic-dashboard:/usr/src/app
    networks:
      - app
    depends_on:
      - traffic-api
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql/
      - ./init_sql.sh:/docker-entrypoint-initdb.d/init_sql.sh
    networks:
      - app
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "$MYSQL_USER",
          "-d",
          "$MYSQL_PASSWORD"
        ]
      interval: 5s
      timeout: 3s
      retries: 5
