<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGrMg7I5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGrMg7I5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGrMg7I5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGrMg7I5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGrMg7I5\App_KernelDevDebugContainer([
    'container.build_hash' => 'GrMg7I5',
    'container.build_id' => '075070f8',
    'container.build_time' => 1744226670,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGrMg7I5');
