<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMU9VWx2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMU9VWx2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMU9VWx2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMU9VWx2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMU9VWx2\App_KernelDevDebugContainer([
    'container.build_hash' => 'MU9VWx2',
    'container.build_id' => 'cfa3e886',
    'container.build_time' => 1743882989,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMU9VWx2');
